/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.todo;

import java.util.ArrayList;
import java.util.List;

public class App {


    private final TaskRepository taskRepository = new TaskRepository();

    public static void main(String[] args) {
        throw  new UnsupportedOperationException();
    }

    public List<String> run() {
        List<Task> loadTasks = taskRepository.loadTasks();
        final var taskList = new ArrayList<String>();
        taskList.add("# To be done");
        for (Task task:loadTasks) {
            taskList.add(task.format());
        }
        return taskList;
    }

}
